class BucketTypes
	SELECT = [['MANAGEMENT', 0],['FINANCIAL', 1],['OPERATIONAL', 2],['INDUSTRY', 3],['PAST_LOAN_PERFORMANCE', 4],['SPECIAL', 5]]
  MANAGEMENT = 0
  FINANCIAL = 1
  OPERATIONAL = 2
  INDUSTRY = 3
  PAST_LOAN_PERFORMANCE = 4
  SPECIAL = 5
end
